language: ruby
sudo: false
rvm:
- '2.2'
before_script:
- npm install bower
- "./node_modules/.bin/bower install"
script: bundle exec middleman build
cache:
  directories:
  - node_modules
  - vendor/bundle
deploy:
  provider: firebase
  skip_cleanup: true
  project:
    master: builtwithpolymer
